#!/usr/bin/env python3
"""Generate the printable phantom film, and everything the analysis needs to read it.

Writes four things into one directory:

    phantom_print.png     the sheet to send to the printer, at the requested dpi
    phantom_build.json    the exact build arguments, so the layout is reproducible
    phantom_truth.npy     the target density map (targets, not what the print carries)
    PRINTING.md           what to print it on, what to tape to it, how to shoot it

Only the first is a physical object and only the second is load-bearing for the
analysis. `phantom_truth.npy` is a convenience for figures: the density the print
*actually* carries is measured from the reference captures, because printer
transfers are nonlinear and device-specific. See `physics/recapture.characterize`.

    python scripts/make_phantom_film.py --out outputs/phantom --print-long-mm 297
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

import numpy as np
from PIL import Image

from tbtrust.physics import findings as FIND
from tbtrust.physics import phantom as PH

PRINTING = """# Printing and shooting the phantom

Generated by `scripts/make_phantom_film.py`. Read this before printing: two of the
steps below are the difference between a sheet the estimator can read and an
expensive piece of plastic.

## Print

* **Transparency film for your printer type** (inkjet film for inkjet, laser film
  for laser). Not paper. The whole rig is a transmission measurement.
* Print `phantom_print.png` at **{long_mm:.0f} mm on the long edge** ({paper}), at the
  highest quality setting, **colour management off / "no colour correction"**.
  Any perceptual rendering intent will re-map the tones and the wedge cannot
  correct for what it did not see.
* Do not scale to fit. The layout is metric and the analysis knows the scale.
* Print **two copies**. The second is the spare, and the pair also tells you how
  repeatable your printer is.

## Assemble (this is the step people skip)

1. **Tape the opaque rim.** The black border on the print is nowhere near opaque
   enough -- a good inkjet reaches about {d_max:.1f} OD and the estimator's beam stop
   assumes film at 3.2 OD, which transmits 6 parts in ten thousand. Lay matte
   black tape, or black card, over the printed rim, following its outer and inner
   edges. Leave the clear "L" marker inside the rim uncovered.
2. **Seat the step wedge** in the outlined lane on the right. Tape it at the ends
   only, emulsion side down, flat against the film. Its 21 steps are the only
   absolutely calibrated thing in the rig; everything this pipeline reports on
   real captures is referred to them.
3. Check by eye against a lightbox: rim optically black, marker clearly the
   brightest thing in the frame, wedge steps all distinguishable.

## Shoot

Two sets, and the distinction matters more than the number of frames.

**Reference set (5 frames).** The best captures you can manage: phone square-on,
centred, film filling the frame, room lights **off**, no window in the room,
exposure and focus locked on the middle of the sheet, no zoom, no flash, HDR off.
These are what the print's densities are measured from, so a mistake here
propagates into every later number. Shoot five and let the analysis discard any
the estimator cannot rectify.

**Test set (the actual experiment).** Vary one thing at a time, ~40 frames total:

| axis | levels |
|---|---|
| phone | at least 2 devices |
| angle | square-on, ~10 deg, ~20 deg off axis |
| distance / framing | film fills the frame, and film at ~60% of frame |
| room light | off, on, and one frame with a window or lamp behind you |
| focus | locked, and one deliberately soft |

Log every frame in the manifest (`data/real_recapture/manifest_template.csv`).
The condition columns are what the analysis groups by; a frame with no row is a
frame that cannot be used.

## Then

```bash
python scripts/validate_real_recapture.py \\
    --phantom {out} --manifest data/real_recapture/manifest.csv \\
    --out outputs/real_recapture
```
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", default="outputs/phantom", help="directory to write into")
    ap.add_argument("--size", type=int, default=2048,
                    help="canonical long-side resolution; the layout's own pixel grid")
    ap.add_argument("--print-long-mm", type=float, default=297.0,
                    help="long edge of the printed sheet in mm (297 = A4 portrait). The layout "
                         "is always in film millimetres, so this only changes what the printer "
                         "has to resolve")
    ap.add_argument("--dpi", type=int, default=600, help="dpi tag written into the PNG")
    ap.add_argument("--d-max-print", type=float, default=PH.D_MAX_PRINT,
                    help="maximum optical density your printer reaches on transparency")
    ap.add_argument("--wedge-mm", default="25.4,127.0",
                    help="physical wedge width,length in mm (default: a Stouffer T2115)")
    ap.add_argument("--wedge-steps", type=int, default=PH.WEDGE_STEPS)
    args = ap.parse_args()

    wedge_mm = tuple(float(v) for v in args.wedge_mm.split(","))
    if len(wedge_mm) != 2:
        print("--wedge-mm wants width,length", file=sys.stderr)
        return 1

    build_args = {
        "size": args.size,
        "print_long_mm": args.print_long_mm,
        "d_max_print": args.d_max_print,
        "wedge_paper_mm": list(wedge_mm),
        "wedge_steps": args.wedge_steps,
    }
    ph = PH.build_from(build_args)
    sane = PH.sanity(ph)

    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    img = Image.fromarray(PH.print_image(ph))
    img.save(out / "phantom_print.png", dpi=(args.dpi, args.dpi))
    np.save(out / "phantom_truth.npy", ph.density)
    (out / "phantom_build.json").write_text(json.dumps(
        {"build": build_args, "spec": ph.spec(), "sanity": sane,
         "findings_on_grid": PH.findings_on_grid(FIND.core(), ph)}, indent=2))
    paper = "A4 portrait" if abs(args.print_long_mm - 297.0) < 1 else f"{args.print_long_mm:.0f} mm long edge"
    (out / "PRINTING.md").write_text(PRINTING.format(
        long_mm=args.print_long_mm, paper=paper, d_max=args.d_max_print, out=out))

    print(f"wrote {out}/phantom_print.png  ({ph.density.shape[1]}x{ph.density.shape[0]} px, "
          f"{args.print_long_mm:.0f} mm long edge at {args.dpi} dpi)")
    print(f"  {sane['n_patches']} detectability discs, {sane['n_steps']} printed steps, "
          f"{args.wedge_steps} wedge steps")
    print(f"  smallest disc: {sane['smallest_patch_mm']} mm of film = "
          f"{sane['smallest_patch_mm_on_paper']} mm on paper "
          f"({sane['smallest_patch_mm_on_paper'] * args.dpi / 25.4:.0f} printer dots across)")

    # The printer, not the layout, is what limits the small end of the size
    # ladder, and it is worth knowing before printing rather than after.
    dots = sane["smallest_patch_mm_on_paper"] * args.dpi / 25.4
    if dots < 12:
        print(f"  WARNING: the smallest disc is only {dots:.0f} dots across. Print larger "
              f"(--print-long-mm) or expect the bottom row of the size ladder to measure "
              f"your printer rather than the phone.")
    for f in PH.findings_on_grid(FIND.core(), ph):
        if not (f["delta_d_bracketed"] and f["size_bracketed"]):
            axes = [n for n, ok in (("contrast", f["delta_d_bracketed"]), ("size", f["size_bracketed"]))
                    if not ok]
            print(f"  note: {f['key']} is off the grid in {' and '.join(axes)}; its verdict will be "
                  f"an extrapolation from {f['nearest_patch']}, not a measurement")
    print(f"\nread {out}/PRINTING.md next -- the opaque rim and the wedge are not optional")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
